package de.rwth.i5.kinectvision.mqtt;


import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.eclipse.paho.client.mqttv3.MqttClient;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.eclipse.paho.client.mqttv3.MqttException;
import org.springframework.beans.factory.annotation.Value;

/**
 * Class used as an MQTT client for the Kinect data. It subscribes to the data generated by the Kinect.
 */
@Slf4j
public class SwevaClient {
    @Setter
    @Value("{mqtt.sweva.broker}")
    private String broker;
    @Setter
    @Value("{mqtt.sweva.client_id}")
    private String clientId;

    /**
     * Initialization method for the MQTT client. Connects to the broker.
     *
     * @throws MqttException
     */
    public void initialize() throws MqttException {
        //Initialize the Mqtt client and establish a connection
        MqttClient kinectClient = new MqttClient(broker, clientId, null);
        MqttConnectOptions connOpts = new MqttConnectOptions();
        connOpts.setCleanSession(true);
        kinectClient.connect(connOpts);
    }

    public void publish() {
        //TODO: Publish method
    }
}
