package de.rwth.i5.kinectvision.robot;

/**
 * This interface is for handling the data generated by the robot.
 */
public interface RobotHandler {
    //TODO: What kind of position data is sent by the robot?

    /**
     * Handling method for position data
     *
     * @param o The data
     */
    public void onPositionEvent(Object o);
}
